# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# for descriptoin here:
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

# Site settings
title: Voca Universe
email: vocacheng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  這個世界需要更多溫柔、悠閒還有腐能量。這個部落格紀錄一個內心戲太多女子的碎碎念以及愛好分享。
  This world needs more tenderness, whatever-ness and bromance. This is a blog that I recorded all little drama in my mind and recommnedations for my hobbies.   
baseurl: "/voca" # the subpath of your site, e.g. /blog
url: "http://vocacheng.me" # the base hostname & protocol for your site
#twitter_username: Taffyer 
#github_username:  wild-flame 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
